window.RADAR = {
 "scannedAt": "2026-10-02T02:12:00+05:30",
 "previousScanAt": "2026-10-02T01:40:00+05:30",
 "sources": [
  "LinkedIn",
  "Wellfound",
  "Cutshort",
  "Company career pages"
 ],
 "jobs": [
  {
   "title": "Senior Product Designer",
   "company": "Supaboard",
   "portal": "Wellfound",
   "posted": "2026-12-02",
   "exp": "4 years",
   "payMinL": 20,
   "payMaxL": 30,
   "level": "Senior",
   "domain": "B2B",
   "url": "https://wellfound.com/jobs/3543172-senior-product-designer",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Sr. User Interaction Design Professional",
   "company": "Siemens Healthineers",
   "portal": "LinkedIn",
   "posted": "2026-10-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Healthcare, enterprise",
   "url": "https://in.linkedin.com/jobs/view/sr-user-interaction-design-professional-at-siemens-healthineers-4472910349",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Skydo",
   "portal": "LinkedIn",
   "posted": "2026-10-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Fintech, cross-border payments",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-skydo-4472553189",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer",
   "company": "Hyreo",
   "portal": "Company site",
   "posted": "2026-10-02",
   "exp": "4–7 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "HR tech",
   "url": "https://job-boards.greenhouse.io/hyreo/jobs/5246996004",
   "note": "Greenhouse · date not shown, open on 2 Oct",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Sarvam AI",
   "portal": "Company site",
   "posted": "2026-10-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "AI, Indian-language models",
   "url": "https://jobs.ashbyhq.com/sarvam/79bb725b-83d4-400c-a207-e2b0a7ccec68",
   "note": "Ashby · date not shown, open on 2 Oct",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Sr. Product Designer – Service Collection",
   "company": "Atlassian",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "B2B SaaS",
   "url": "https://in.linkedin.com/jobs/view/sr-product-designer-service-collection-at-atlassian-4474136923",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer",
   "company": "CrashPlan",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "SaaS, data backup",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-at-crashplan-4474389919",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer, RBS",
   "company": "Amazon",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "E-commerce",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-rbs-at-amazon-4455794253",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Sr. UX Designer – Amazon Now",
   "company": "Amazon",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Quick commerce",
   "url": "https://in.linkedin.com/jobs/view/sr-ux-designer-amazon-now-amazon-now-at-amazon-4455794311",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Sr. User Experience Design Professional",
   "company": "Siemens Healthineers",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Healthcare, enterprise",
   "url": "https://in.linkedin.com/jobs/view/sr-user-experience-design-professional-at-siemens-healthineers-4472900794",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX / Product Designer – Consumer Commerce (200M+ users)",
   "company": "CareerXperts Consulting",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Consumer commerce",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-product-designer-consumer-commerce-at-200m%2B-user-scale-at-careerxperts-consulting-4472929516",
   "note": "Recruiter posting",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Product Designer",
   "company": "Navan",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Travel & expense SaaS",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-navan-4456150927",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UX Product Designer, MX Player",
   "company": "Prime Video & Amazon MGM Studios",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Media, streaming",
   "url": "https://in.linkedin.com/jobs/view/ux-product-designer-mx-player-at-prime-video-amazon-mgm-studios-4473977879",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Founding Product Designer (3+ yrs)",
   "company": "Scalio",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "3+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Startup",
   "url": "https://in.linkedin.com/jobs/view/founding-product-designer-3%2B-yoe-at-scalio-4472530615",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "slice",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-slice-4473776716",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "JioStar",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Media, streaming",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-jiostar-4438058979",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Aspora",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech, remittance",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-aspora-4428813846",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Greenlight",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "5–7 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech, family banking",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-greenlight-4473580878",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer – B2C",
   "company": "Versatile Club (EOR)",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "B2C",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-b2c-at-versatile-club-employer-of-record-4473744435",
   "note": "3 similar postings",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer (B2C)",
   "company": "Versatile Club Employer of Record",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "B2C",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-b2c-at-versatile-club-employer-of-record-4473746968",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Runable",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "3–6 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "SaaS",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-runable-4472128205",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "User Experience Designer",
   "company": "Trane Technologies",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "5-7 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Sustainability",
   "url": "https://in.linkedin.com/jobs/view/user-experience-designer-at-trane-technologies-4454261654",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff/Principal Product Designer",
   "company": "Versatile Club (EOR)",
   "portal": "LinkedIn",
   "posted": "2026-09-29",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Product",
   "url": "https://in.linkedin.com/jobs/view/staff-principal-product-designer-at-versatile-club-employer-of-record-4473213429",
   "note": "3 similar postings",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff/Principal Product Designer",
   "company": "Versatile Club Employer of Record",
   "portal": "LinkedIn",
   "posted": "2026-09-29",
   "exp": "8–12+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "InsurTech",
   "url": "https://in.linkedin.com/jobs/view/staff-principal-product-designer-at-versatile-club-employer-of-record-4473211468",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "MyYogaTeacher",
   "portal": "LinkedIn",
   "posted": "2026-09-28",
   "exp": "5-8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Health & Wellness",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-myyogateacher-4472498104",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Design Lead, Platform Tools",
   "company": "Rippling",
   "portal": "LinkedIn",
   "posted": "2026-09-27",
   "exp": "8+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "SaaS Platform",
   "url": "https://in.linkedin.com/jobs/view/product-design-lead-platform-tools-at-rippling-4454889888",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Engineer, User Experience & Design - Mobile",
   "company": "Vontier",
   "portal": "LinkedIn",
   "posted": "2026-09-27",
   "exp": "5+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "B2B SaaS",
   "url": "https://in.linkedin.com/jobs/view/staff-engineer-user-experience-design-mobile-at-vontier-4435824093",
   "note": "Remote",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer",
   "company": "Motorola Solutions",
   "portal": "LinkedIn",
   "posted": "2026-09-26",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Enterprise, public safety",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-at-motorola-solutions-4432581924",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer",
   "company": "MakeMyTrip",
   "portal": "LinkedIn",
   "posted": "2026-09-26",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Travel",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-at-makemytrip-4471888686",
   "note": "Second opening posted 2 weeks ago",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UX Product Designer (Networking)",
   "company": "Hewlett Packard Enterprise",
   "portal": "LinkedIn",
   "posted": "2026-09-26",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Enterprise networking",
   "url": "https://in.linkedin.com/jobs/view/ux-product-designer-networking-at-hewlett-packard-enterprise-4471887481",
   "note": "Also on Built In",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead Product Designer",
   "company": "Scapia",
   "portal": "LinkedIn",
   "posted": "2026-09-26",
   "exp": "8–12+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Travel",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-scapia-4471403133",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UI/UX Designer – AI Hub",
   "company": "Linde",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Industrial, AI",
   "url": "https://in.linkedin.com/jobs/view/senior-ui-ux-designer-ai-hub-at-linde-4463107633",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Designer",
   "company": "Bytebeam",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "IoT platform",
   "url": "https://in.linkedin.com/jobs/view/senior-designer-at-bytebeam-4468548579",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer",
   "company": "OneTrust",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "B2B SaaS, privacy",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-at-onetrust-4470636485",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff UX Designer",
   "company": "OneTrust",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "B2B SaaS, privacy",
   "url": "https://in.linkedin.com/jobs/view/staff-ux-designer-at-onetrust-4454063112",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Jupiter",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Fintech",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-jupiter-4467376442",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer (UI/UX)",
   "company": "Lyzr AI",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "AI agents",
   "url": "https://in.linkedin.com/jobs/view/product-designer-ui-ux-at-lyzr-ai-4468516680",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Cradlewise",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Consumer hardware",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-cradlewise-4467844521",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UI / UX Designer - AI Hub",
   "company": "Linde@India",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI",
   "url": "https://in.linkedin.com/jobs/view/senior-ui-ux-designer-ai-hub-at-linde%40india-4461103201",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "User Experience Designer",
   "company": "Accenture in India",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "3 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "IT Services",
   "url": "https://in.linkedin.com/jobs/view/user-experience-designer-at-accenture-in-india-4448390474",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UI / UX designer",
   "company": "Emplay",
   "portal": "Wellfound",
   "posted": "2026-09-25",
   "exp": "3 yrs",
   "payMinL": 3,
   "payMaxL": 6.5,
   "level": "Mid",
   "domain": "B2B",
   "url": "https://wellfound.com/jobs/4751198-ui-ux-designer",
   "note": "Remote",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Emirates NBD",
   "portal": "LinkedIn",
   "posted": "2026-09-24",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Banking",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-emirates-nbd-4469399546",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Design Engineer",
   "company": "NeoGenCode Technologies",
   "portal": "Cutshort",
   "posted": "2026-09-24",
   "exp": "4–8 yrs",
   "payMinL": 30,
   "payMaxL": 50,
   "level": "Senior",
   "domain": "Design + frontend",
   "url": "https://cutshort.io/job/Senior-Product-Design-Engineer-Bengaluru-Bangalore-NeoGenCode-Technologies-Pvt-Ltd-IHD4CSNt",
   "note": "Hybrid · needs coding",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Namma Yatri",
   "portal": "LinkedIn",
   "posted": "2026-09-24",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Mobility",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-namma-yatri-4469395474",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UX Designer 2",
   "company": "Nutanix",
   "portal": "LinkedIn",
   "posted": "2026-09-24",
   "exp": "2+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Cloud Software",
   "url": "https://in.linkedin.com/jobs/view/ux-designer-2-at-nutanix-4469705161",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer | Early-Stage MusicTech Portfolio Company",
   "company": "Peak XV Partners",
   "portal": "LinkedIn",
   "posted": "2026-09-24",
   "exp": "5–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "MusicTech",
   "url": "https://in.linkedin.com/jobs/view/product-designer-early-stage-musictech-portfolio-company-at-peak-xv-partners-4469696097",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior User Experience Designer",
   "company": "HCLTech",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "IT services",
   "url": "https://in.linkedin.com/jobs/view/senior-user-experience-designer-at-hcltech-4469343122",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer II",
   "company": "Nielsen",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Data, media",
   "url": "https://in.linkedin.com/jobs/view/product-designer-ii-at-nielsen-4459958590",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer II",
   "company": "JioHotstar",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Media, streaming",
   "url": "https://in.linkedin.com/jobs/view/product-designer-ii-at-jiohotstar-4468986566",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Product Designer",
   "company": "ServiceTitan",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Vertical SaaS",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-servicetitan-4470922678",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UX Designer - C3 - CXP",
   "company": "Valtech",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "5–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Experience Innovation",
   "url": "https://in.linkedin.com/jobs/view/ux-designer-c3-cxp-at-valtech-4461735412",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead Product Designer",
   "company": "Meesho",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "6+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "E-commerce",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-meesho-4470985311",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Healthify",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Health, consumer",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-healthify-4470463498",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Menlo Security",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Cybersecurity, B2B",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-menlo-security-inc-4452406203",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Think Design Collaborative",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Design agency",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-think-design-collaborative-4470251425",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer – Fi Admin",
   "company": "Candescent",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Banking software",
   "url": "https://in.linkedin.com/jobs/view/product-designer-fi-admin-at-candescent-4470284182",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead – Product Designer",
   "company": "Freshworks",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "B2B SaaS",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-freshworks-4467044606",
   "note": "2 openings",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead Product Designer",
   "company": "Josys",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "IT management SaaS",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-josys-4469040520",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "JazzX AI",
   "portal": "LinkedIn",
   "posted": "2026-09-21",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-jazzx-ai-4467375690",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead Product Designer",
   "company": "noon",
   "portal": "LinkedIn",
   "posted": "2026-09-21",
   "exp": "6+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "E-commerce",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-noon-4469899160",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead UX Designer",
   "company": "Consilio LLC",
   "portal": "LinkedIn",
   "posted": "2026-09-21",
   "exp": "8+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Legal Tech",
   "url": "https://in.linkedin.com/jobs/view/lead-ux-designer-at-consilio-llc-4469913386",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UX Designer, YouTube Creator Support",
   "company": "Google",
   "portal": "LinkedIn",
   "posted": "2026-09-21",
   "exp": "4 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI",
   "url": "https://in.linkedin.com/jobs/view/ux-designer-youtube-creator-support-at-google-4468499694",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "AiDASH",
   "portal": "LinkedIn",
   "posted": "2026-09-20",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI, climate",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-aidash-4469804820",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Principal UX Designer (NetSec)",
   "company": "Palo Alto Networks",
   "portal": "LinkedIn",
   "posted": "2026-09-20",
   "exp": "10+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Cybersecurity",
   "url": "https://in.linkedin.com/jobs/view/principal-ux-designer-netsec-at-palo-alto-networks-4402818442",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Product Designer",
   "company": "Adobe",
   "portal": "LinkedIn",
   "posted": "2026-09-19",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Creative software",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-adobe-4321974489",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Design Engineer (Design, Frontend)",
   "company": "Staffnix",
   "portal": "Cutshort",
   "posted": "2026-09-19",
   "exp": "4–8 yrs",
   "payMinL": 40,
   "payMaxL": 50,
   "level": "Senior",
   "domain": "Design + frontend",
   "url": "https://cutshort.io/job/Senior-Product-Design-Engineer-Design-Frontend-Bengaluru-Bangalore-Staffnixcom-kbG17zf9",
   "note": "Recruiter · needs coding",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Yulu",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "EV mobility",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-yulu-4468606404",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Xometry",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "B2B marketplace",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-xometry-4461334468",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Product Designer",
   "company": "JazzX AI",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "AI",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-jazzx-ai-4463950753",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Atlys",
   "portal": "Wellfound",
   "posted": "2026-09-18",
   "exp": "2 years",
   "payMinL": 30,
   "payMaxL": 80,
   "level": "Mid",
   "domain": "B2C B2B",
   "url": "https://wellfound.com/jobs/4144519-product-designer",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer 2",
   "company": "Truemeds",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Health, pharmacy",
   "url": "https://in.linkedin.com/jobs/view/product-designer-2-at-truemeds-4463973910",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer – AI and Enterprise Software",
   "company": "Thermo Fisher Scientific",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Life sciences, enterprise",
   "url": "https://in.linkedin.com/jobs/view/product-designer-ai-and-enterprise-software-job-posting-title-here-at-thermo-fisher-scientific-4464274964",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Principal Product Designer",
   "company": "Epicor",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Enterprise software",
   "url": "https://in.linkedin.com/jobs/view/principal-product-designer-at-epicor-4428814504",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Design Engineer",
   "company": "Delightree",
   "portal": "Wellfound",
   "posted": "2026-09-18",
   "exp": "4 yrs",
   "payMinL": 40,
   "payMaxL": 50,
   "level": "Senior",
   "domain": "Operations mgmt",
   "url": "https://wellfound.com/jobs/4701950-senior-design-engineer",
   "note": "In office needs coding",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UI/UX Designer",
   "company": "Gnapi Technologies",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "5+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "IT Services",
   "url": "https://in.linkedin.com/jobs/view/ui-ux-designer-at-gnapi-technologies-4469153014",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Design Manager - UX, Product Design",
   "company": "PhonePe",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "7–10 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Fintech",
   "url": "https://in.linkedin.com/jobs/view/product-design-manager-ux-product-design-at-phonepe-4458093175",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UI/UX Designer",
   "company": "Wesence",
   "portal": "Wellfound",
   "posted": "2026-09-18",
   "exp": "3 yrs",
   "payMinL": 6,
   "payMaxL": 7.2,
   "level": "Mid",
   "domain": "Intelligent Systems",
   "url": "https://wellfound.com/jobs/4718643-ui-ux-product-designer",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead I – UX Design",
   "company": "UST",
   "portal": "LinkedIn",
   "posted": "2026-09-17",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "IT services",
   "url": "https://in.linkedin.com/jobs/view/lead-i-ux-design-at-ust-4448073143",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Product Designer",
   "company": "JioStar",
   "portal": "LinkedIn",
   "posted": "2026-09-16",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Media, streaming",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-jiostar-4465966715",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UI/UX Designer",
   "company": "Ecolab",
   "portal": "LinkedIn",
   "posted": "2026-09-16",
   "exp": "3+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Enterprise Software",
   "url": "https://in.linkedin.com/jobs/view/ui-ux-designer-at-ecolab-4468254051",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UI/UX Designer",
   "company": "JOOLA",
   "portal": "LinkedIn",
   "posted": "2026-09-16",
   "exp": "6-10+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "E-commerce",
   "url": "https://in.linkedin.com/jobs/view/ui-ux-designer-at-joola-4467951913",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer (UX/UI)",
   "company": "Revun",
   "portal": "LinkedIn",
   "posted": "2026-09-15",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "SaaS",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-ux-ui-at-revun-4458703085",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Mumzworld",
   "portal": "LinkedIn",
   "posted": "2026-09-15",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "E-commerce",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-mumzworld-com-4466158632",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer",
   "company": "Myntra",
   "portal": "LinkedIn",
   "posted": "2026-09-15",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fashion e-commerce",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-at-myntra-4448859154",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Ema",
   "portal": "LinkedIn",
   "posted": "2026-09-15",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "AI, enterprise",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-ema-4465940221",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "noon",
   "portal": "LinkedIn",
   "posted": "2026-09-14",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "E-commerce",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-noon-4467030748",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Rapido",
   "portal": "LinkedIn",
   "posted": "2026-09-11",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Mobility, consumer",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-rapido-4464865223",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Platform Product Designer",
   "company": "JazzX AI",
   "portal": "LinkedIn",
   "posted": "2026-09-11",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "AI platform",
   "url": "https://in.linkedin.com/jobs/view/platform-product-designer-at-jazzx-ai-4463970068",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Product Designer",
   "company": "Moniepoint",
   "portal": "LinkedIn",
   "posted": "2026-09-11",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Fintech",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-moniepoint-group-4463991460",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead Product Designer",
   "company": "FOXO",
   "portal": "Wellfound",
   "posted": "2026-09-11",
   "exp": "8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Longevity",
   "url": "https://wellfound.com/jobs/4689777-lead-product-designer",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "WorkIndia",
   "portal": "LinkedIn",
   "posted": "2026-09-11",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Jobs marketplace",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-workindia-4465632362",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Sr UX Designer – Advanced AI",
   "company": "Target",
   "portal": "LinkedIn",
   "posted": "2026-09-10",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Retail, AI",
   "url": "https://in.linkedin.com/jobs/view/sr-ux-designer-advanced-ai-at-target-4460298097",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior User Experience Designer",
   "company": "redBus",
   "portal": "LinkedIn",
   "posted": "2026-09-10",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Travel",
   "url": "https://in.linkedin.com/jobs/view/senior-user-experience-designer-at-redbus-4464193049",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Tekion",
   "portal": "LinkedIn",
   "posted": "2026-09-10",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Automotive SaaS",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-tekion-corp-4463481049",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Greytip (greytHR)",
   "portal": "LinkedIn",
   "posted": "2026-09-10",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "HR SaaS",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-greytip-software-private-limited-4465621168",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer II",
   "company": "Tekion",
   "portal": "LinkedIn",
   "posted": "2026-09-10",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Automotive SaaS",
   "url": "https://in.linkedin.com/jobs/view/product-designer-ii-at-tekion-corp-4463471044",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Lenskart",
   "portal": "LinkedIn",
   "posted": "2026-09-09",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Retail, e-commerce",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-lenskart-com-4463034182",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead Product Designer",
   "company": "GREYTIP SOFTWARE PRIVATE LIMITED",
   "portal": "LinkedIn",
   "posted": "2026-09-09",
   "exp": "8–10 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "HR Tech SaaS",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-greytip-software-private-limited-4464972772",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Fam",
   "portal": "LinkedIn",
   "posted": "2026-09-08",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-fam-4463247310",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer – India",
   "company": "Anatta",
   "portal": "LinkedIn",
   "posted": "2026-09-08",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Shopify agency",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-india-at-anatta-shopify-platinum-partner-4463065016",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Nava",
   "portal": "LinkedIn",
   "posted": "2026-09-07",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Startup",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-nava-4462940225",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer",
   "company": "Bridgestone Americas",
   "portal": "LinkedIn",
   "posted": "2026-09-06",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Enterprise",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-at-bridgestone-americas-4462680228",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead Product Designer",
   "company": "PhysicsWallah",
   "portal": "LinkedIn",
   "posted": "2026-09-04",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Edtech",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-pw-physicswallah-4463346830",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior User Experience Designer II",
   "company": "Schneider Electric",
   "portal": "LinkedIn",
   "posted": "2026-09-03",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Energy, enterprise",
   "url": "https://in.linkedin.com/jobs/view/senior-user-experience-designer-ii-at-schneider-electric-4461627521",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Hevo Data",
   "portal": "Company site",
   "posted": "2026-09-02",
   "exp": "4–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Data SaaS, AI-first",
   "url": "https://jobs.lever.co/hevodata/3c22a84f-7eb6-4105-aa3b-7698322a98af",
   "note": "On-site 5 days, HSR Layout · also on LinkedIn",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Experience Designer, SC Design (UI/UX)",
   "company": "Standard Chartered",
   "portal": "LinkedIn",
   "posted": "2026-09-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Banking",
   "url": "https://in.linkedin.com/jobs/view/senior-experience-designer-sc-design-ui-ux-at-standard-chartered-india-4460244922",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Get My Parking",
   "portal": "Wellfound",
   "posted": "2026-09-02",
   "exp": "5 yrs",
   "payMinL": 15,
   "payMaxL": 20,
   "level": "Senior",
   "domain": "AI",
   "url": "https://wellfound.com/jobs/747214-senior-product-designer",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "AI Product Designer — Founding Member, BrandBrahma",
   "company": "BrandBrahma",
   "portal": "Wellfound",
   "posted": "2026-09-02",
   "exp": "3 yrs",
   "payMinL": 8,
   "payMaxL": 20,
   "level": "Mid",
   "domain": "AI",
   "url": "https://wellfound.com/jobs/4505597-product-designer-founding-member-brandbrahma",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead Product Designer",
   "company": "Dashverse",
   "portal": "LinkedIn",
   "posted": "2026-09-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Consumer AI",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-dashverse-4448825208",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "SE Intel UX UI Designer",
   "company": "Schneider Electric",
   "portal": "LinkedIn",
   "posted": "2026-09-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Digital Experience",
   "url": "https://in.linkedin.com/jobs/view/se-intel-ux-ui-designer-at-schneider-electric-4460622458",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Sarvam",
   "portal": "LinkedIn",
   "posted": "2026-08-19",
   "exp": "4+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-sarvam-4456176299",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UX/UI Designer",
   "company": "Apple",
   "portal": "LinkedIn",
   "posted": "2026-08-19",
   "exp": "1+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Manufacturing Data",
   "url": "https://in.linkedin.com/jobs/view/ux-ui-designer-at-apple-4454938841",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "StockGro",
   "portal": "LinkedIn",
   "posted": "2026-08-07",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech, investing",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-stockgro-4430921229",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Finkraft",
   "portal": "LinkedIn",
   "posted": "2026-08-05",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech, B2B",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-finkraft-4433468110",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Product Designer",
   "company": "EarnIn",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "B2C",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-earnin-4443581994",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "FOXO",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "4 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Longevity",
   "url": "https://wellfound.com/jobs/4053124-product-designer",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff/Principal Product Designer, Partnerships",
   "company": "Ethos",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "B2C",
   "url": "https://wellfound.com/jobs/4670517-staff-principal-product-designer-partnerships",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UI/UX Designer",
   "company": "ENFLIX",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "5 yrs",
   "payMinL": 11,
   "payMaxL": 14,
   "level": "Senior",
   "domain": "Entertainment",
   "url": "https://wellfound.com/jobs/4479275-senior-ui-ux-designer",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product UI/UX Designer",
   "company": "Outdoo AI",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "2 yrs",
   "payMinL": 20,
   "payMaxL": 30,
   "level": "Senior",
   "domain": "AI",
   "url": "https://wellfound.com/jobs/2976208-senior-product-ui-ux-designer",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Fireflies.ai",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "3 years",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "B2B",
   "url": "https://wellfound.com/jobs/3281427-product-designer",
   "note": "Remote",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Corvee",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "B2B",
   "url": "https://wellfound.com/jobs/3344993-product-designer",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Software Engineer/ Product Engineer",
   "company": "rooh",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "3 years",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Platform",
   "url": "https://wellfound.com/jobs/4420099-software-engineer-product-engineer",
   "note": "Remote needs coding",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer / UI-UX Designer",
   "company": "rooh",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "3 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "B2B",
   "url": "https://wellfound.com/jobs/4418963-product-designer-ui-ux-designer",
   "note": "Remote",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Engineer",
   "company": "Troopod",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "0 years",
   "payMinL": 3.5,
   "payMaxL": 12,
   "level": "Mid",
   "domain": "AI",
   "url": "https://wellfound.com/jobs/4521224-product-engineer-clone",
   "note": "Remote needs coding",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Engineer",
   "company": "Troopod",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "0 years",
   "payMinL": 3.5,
   "payMaxL": 12,
   "level": "Senior",
   "domain": "AI",
   "url": "https://wellfound.com/jobs/4521223-senior-product-engineer-clone",
   "note": "Remote needs coding",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UI/UX Designer (Engineering Platforms)",
   "company": "ENGINPILOT",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "3 yrs",
   "payMinL": 0.2,
   "payMaxL": 0.3,
   "level": "Mid",
   "domain": "Physical Assets",
   "url": "https://wellfound.com/jobs/4435452-ui-ux-designer-engineering-platforms",
   "note": "In office needs coding",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior AI Product Engineer",
   "company": "Propel",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "5 yrs",
   "payMinL": 35,
   "payMaxL": 40,
   "level": "Senior",
   "domain": "AI",
   "url": "https://wellfound.com/jobs/4275942-senior-ai-product-engineer",
   "note": "In office needs coding",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "GreyLabs AI",
   "portal": "LinkedIn",
   "posted": "2026-07-31",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI, conversation analytics",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-greylabs-ai-4447513416",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UI/UX Designer",
   "company": "ADA",
   "portal": "LinkedIn",
   "posted": "2026-07-31",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Digital agency",
   "url": "https://in.linkedin.com/jobs/view/senior-ui-ux-designer-at-ada-4446996414",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Sr. UX Designer",
   "company": "Eightfold AI",
   "portal": "LinkedIn",
   "posted": "2026-07-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI, HR tech",
   "url": "https://in.linkedin.com/jobs/view/sr-ux-designer-at-eightfold-ai-4445326692",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "A&CD - UX Design Lead (Contract",
   "company": "Alstom",
   "portal": "LinkedIn",
   "posted": "2026-07-21",
   "exp": "8+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Transportation",
   "url": "https://in.linkedin.com/jobs/view/a-cd-ux-design-lead-contract-at-alstom-4440489795",
   "note": "Contract",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UI/UX Designer",
   "company": "Squadra Media",
   "portal": "LinkedIn",
   "posted": "2026-07-15",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Media",
   "url": "https://in.linkedin.com/jobs/view/senior-ui-ux-designer-at-squadra-media-4440205926",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer",
   "company": "Mirorin",
   "portal": "Cutshort",
   "posted": "2026-06-22",
   "exp": "5+ yrs",
   "payMinL": 6,
   "payMaxL": 9,
   "level": "Senior",
   "domain": "FemTech",
   "url": "https://cutshort.io/jobs/product-design-jobs",
   "note": "",
   "firstSeen": "2026-10-02"
  }
 ]
};
