window.RADAR = {
 "scannedAt": "2026-10-04T15:34:00+05:30",
 "previousScanAt": "2026-10-03T14:54:00+05:30",
 "sources": [
  "LinkedIn",
  "Wellfound",
  "Cutshort",
  "Company career pages"
 ],
 "jobs": [
  {
   "title": "Senior Product Designer",
   "company": "Supaboard",
   "portal": "Wellfound",
   "posted": "2026-10-04",
   "exp": "4 yrs",
   "payMinL": 20,
   "payMaxL": 30,
   "level": "Senior",
   "domain": "Data Analytics",
   "url": "https://wellfound.com/jobs/3543172-senior-product-designer",
   "note": "In office",
   "firstSeen": "2026-10-04"
  },
  {
   "title": "Senior UI / Product Designer",
   "company": "ARADY",
   "portal": "Instahyre",
   "posted": "2026-10-04",
   "exp": "7+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Real estate",
   "url": "https://www.instahyre.com/job-442683-senior-ui-product-designer-at-arady-bangalore/",
   "note": "",
   "firstSeen": "2026-10-04"
  },
  {
   "title": "Sr. User Interaction Design Professional",
   "company": "Siemens Healthineers",
   "portal": "LinkedIn",
   "posted": "2026-10-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Healthcare, enterprise",
   "url": "https://in.linkedin.com/jobs/view/sr-user-interaction-design-professional-at-siemens-healthineers-4472910349",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer",
   "company": "Skydo",
   "portal": "LinkedIn",
   "posted": "2026-10-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Fintech, cross-border payments",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-skydo-4472553189",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "UX Designer",
   "company": "Komprise",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "4-8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Enterprise SaaS",
   "url": "https://www.instahyre.com/job-445363-ux-designer-at-komprise-bangalore/",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Bridgetown Research",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "4-7 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI, SaaS",
   "url": "https://www.instahyre.com/job-442801-senior-product-designer-at-bridgetown-research-bangalore/",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "NuPlay AI",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "5-9 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI",
   "url": "https://www.instahyre.com/job-444986-product-designer-at-nuplay-ai-bangalore/",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Toddle",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "1-5 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Education SaaS",
   "url": "https://www.instahyre.com/job-422868-product-designer-at-toddle-bangalore/",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Tradl AI",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "4-6+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech",
   "url": "https://www.instahyre.com/job-429081-senior-product-designer-at-tradl-ai-bangalore/",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Design Manager",
   "company": "Bigbasket.com",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "8+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "E-commerce",
   "url": "https://www.instahyre.com/job-429193-product-design-manager-at-bigbasket-bangalore/",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Matters",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "8-12 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "B2B SaaS",
   "url": "https://www.instahyre.com/job-444996-senior-product-designer-at-matters-bangalore/",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Subscribili",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "6-8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "B2B SaaS",
   "url": "https://www.instahyre.com/job-442289-senior-product-designer-at-subscribili-bangalore/",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Sahi",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "4-8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Trading Platform",
   "url": "https://www.instahyre.com/job-438241-senior-product-designer-at-sahi-bangalore/",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Principal Product Designer",
   "company": "Moveworks",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "15+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "AI",
   "url": "https://www.instahyre.com/job-432735-principal-product-designer-at-moveworks-bangalore/",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Supernova",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "3-7 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Edtech",
   "url": "https://www.instahyre.com/job-444010-product-designer-at-supernova-bangalore/",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Innovaccer",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "8+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Healthcare",
   "url": "https://www.instahyre.com/job-432841-product-designer-at-innovaccer-2-bangalore/",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "PolicyBazaar.com",
   "portal": "Instahyre",
   "posted": "2026-10-02",
   "exp": "7+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech",
   "url": "https://www.instahyre.com/job-409585-product-designer-at-policybazaar-bangalore/",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Product Designer",
   "company": "Moniepoint",
   "portal": "LinkedIn",
   "posted": "2026-10-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Fintech",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-moniepoint-group-4463991460",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Sr. Product Designer – Service Collection",
   "company": "Atlassian",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "B2B SaaS",
   "url": "https://in.linkedin.com/jobs/view/sr-product-designer-service-collection-at-atlassian-4474136923",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior UX Designer",
   "company": "CrashPlan",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "SaaS, data backup",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-at-crashplan-4474389919",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Sr. UX Designer – Amazon Now",
   "company": "Amazon",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Quick commerce",
   "url": "https://in.linkedin.com/jobs/view/sr-ux-designer-amazon-now-amazon-now-at-amazon-4455794311",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Sr. User Experience Design Professional",
   "company": "Siemens Healthineers",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Healthcare, enterprise",
   "url": "https://in.linkedin.com/jobs/view/sr-user-experience-design-professional-at-siemens-healthineers-4472900794",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior UX / Product Designer – Consumer Commerce (200M+ users)",
   "company": "CareerXperts Consulting",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Consumer commerce",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-product-designer-consumer-commerce-at-200m%2B-user-scale-at-careerxperts-consulting-4472929516",
   "note": "Recruiter posting",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Staff Product Designer",
   "company": "Navan",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Travel & expense SaaS",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-navan-4456150927",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "UX Product Designer, MX Player",
   "company": "Prime Video & Amazon MGM Studios",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Media, streaming",
   "url": "https://in.linkedin.com/jobs/view/ux-product-designer-mx-player-at-prime-video-amazon-mgm-studios-4473977879",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Founding Product Designer (3+ yrs)",
   "company": "Scalio",
   "portal": "LinkedIn",
   "posted": "2026-10-01",
   "exp": "3+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Startup",
   "url": "https://in.linkedin.com/jobs/view/founding-product-designer-3%2B-yoe-at-scalio-4472530615",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "slice",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-slice-4473776716",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "JioStar",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Media, streaming",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-jiostar-4438058979",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "Aspora",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech, remittance",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-aspora-4428813846",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "Greenlight",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "5–7 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech, family banking",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-greenlight-4473580878",
   "note": "Hybrid",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer – B2C",
   "company": "Versatile Club (EOR)",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "B2C",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-b2c-at-versatile-club-employer-of-record-4473744435",
   "note": "3 similar postings · Recruiter",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer (B2C)",
   "company": "Versatile Club Employer of Record",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "B2C",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-b2c-at-versatile-club-employer-of-record-4473746968",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Runable",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "3–6 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "SaaS",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-runable-4472128205",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "User Experience Designer",
   "company": "Trane Technologies",
   "portal": "LinkedIn",
   "posted": "2026-09-30",
   "exp": "5-7 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Sustainability",
   "url": "https://in.linkedin.com/jobs/view/user-experience-designer-at-trane-technologies-4454261654",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "CG-VAK Software & Exports",
   "portal": "Hirist",
   "posted": "2026-09-30",
   "exp": "4–6 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "",
   "url": "https://www.hirist.tech/j/c-g-vak-softwares-exports-product-designer-1676147",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior/Lead Product Designer - Prototyping Tools",
   "company": "Arting Digital",
   "portal": "Hirist",
   "posted": "2026-09-30",
   "exp": "8–13 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Prototyping Tools",
   "url": "https://www.hirist.tech/j/seniorlead-product-designer-prototyping-tools-1676066",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UX Product Designer, MX Player",
   "company": "Amazon",
   "portal": "Amazon Jobs",
   "posted": "2026-09-30",
   "exp": "3+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Entertainment",
   "url": "https://www.amazon.jobs/en/jobs/10565933/ux-product-designer-mx-player",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff/Principal Product Designer",
   "company": "Versatile Club (EOR)",
   "portal": "LinkedIn",
   "posted": "2026-09-29",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Product",
   "url": "https://in.linkedin.com/jobs/view/staff-principal-product-designer-at-versatile-club-employer-of-record-4473213429",
   "note": "3 similar postings · Recruiter",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Staff/Principal Product Designer",
   "company": "Versatile Club Employer of Record",
   "portal": "LinkedIn",
   "posted": "2026-09-29",
   "exp": "8–12+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "InsurTech",
   "url": "https://in.linkedin.com/jobs/view/staff-principal-product-designer-at-versatile-club-employer-of-record-4473211468",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "MyYogaTeacher",
   "portal": "LinkedIn",
   "posted": "2026-09-28",
   "exp": "5-8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Health & Wellness",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-myyogateacher-4472498104",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer - Prototyping Tools",
   "company": "Nykaa",
   "portal": "Hirist",
   "posted": "2026-09-28",
   "exp": "2–4 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "E-commerce",
   "url": "https://www.hirist.tech/j/nykaa-product-designer-prototyping-tools-1674928",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Product Designer",
   "company": "Vigoursoft Global Solutions",
   "portal": "Hirist",
   "posted": "2026-09-28",
   "exp": "8–20 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "",
   "url": "https://www.hirist.tech/j/vigoursoft-global-solutions-staff-product-designer-1675195",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Design Lead, Platform Tools",
   "company": "Rippling",
   "portal": "LinkedIn",
   "posted": "2026-09-27",
   "exp": "8+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "SaaS Platform",
   "url": "https://in.linkedin.com/jobs/view/product-design-lead-platform-tools-at-rippling-4454889888",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Engineer, User Experience & Design - Mobile",
   "company": "Vontier",
   "portal": "LinkedIn",
   "posted": "2026-09-27",
   "exp": "5+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "B2B SaaS",
   "url": "https://in.linkedin.com/jobs/view/staff-engineer-user-experience-design-mobile-at-vontier-4435824093",
   "note": "Remote",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer",
   "company": "Motorola Solutions",
   "portal": "LinkedIn",
   "posted": "2026-09-26",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Enterprise, public safety",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-at-motorola-solutions-4432581924",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "UX Product Designer (Networking)",
   "company": "Hewlett Packard Enterprise",
   "portal": "LinkedIn",
   "posted": "2026-09-26",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Enterprise networking",
   "url": "https://in.linkedin.com/jobs/view/ux-product-designer-networking-at-hewlett-packard-enterprise-4471887481",
   "note": "Also on Built In",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Lead Product Designer",
   "company": "Scapia",
   "portal": "LinkedIn",
   "posted": "2026-09-26",
   "exp": "8–12+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Travel",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-scapia-4471403133",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UI/UX Designer – AI Hub",
   "company": "Linde",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Industrial, AI",
   "url": "https://in.linkedin.com/jobs/view/senior-ui-ux-designer-ai-hub-at-linde-4463107633",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior UX Designer",
   "company": "OneTrust",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "B2B SaaS, privacy",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-at-onetrust-4470636485",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Staff UX Designer",
   "company": "OneTrust",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "B2B SaaS, privacy",
   "url": "https://in.linkedin.com/jobs/view/staff-ux-designer-at-onetrust-4454063112",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer",
   "company": "Jupiter",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Fintech",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-jupiter-4467376442",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer",
   "company": "Cradlewise",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Consumer hardware",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-cradlewise-4467844521",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior UI / UX Designer - AI Hub",
   "company": "Linde@India",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI",
   "url": "https://in.linkedin.com/jobs/view/senior-ui-ux-designer-ai-hub-at-linde%40india-4461103201",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "User Experience Designer",
   "company": "Accenture in India",
   "portal": "LinkedIn",
   "posted": "2026-09-25",
   "exp": "3 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "IT Services",
   "url": "https://in.linkedin.com/jobs/view/user-experience-designer-at-accenture-in-india-4448390474",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer, Amazon Pay India",
   "company": "Amazon",
   "portal": "Amazon Jobs",
   "posted": "2026-09-25",
   "exp": "7+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech",
   "url": "https://www.amazon.jobs/en/jobs/10560185/product-designer-amazon-pay-india",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff UX Designer",
   "company": "Okta",
   "portal": "Company site",
   "posted": "2026-09-25",
   "exp": "8+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Identity Security",
   "url": "https://www.okta.com/company/careers/opportunity/8232605?gh_jid=8232605",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Emirates NBD",
   "portal": "LinkedIn",
   "posted": "2026-09-24",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Banking",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-emirates-nbd-4469399546",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Design Engineer",
   "company": "NeoGenCode Technologies",
   "portal": "Cutshort",
   "posted": "2026-09-24",
   "exp": "4–8 yrs",
   "payMinL": 30,
   "payMaxL": 50,
   "level": "Senior",
   "domain": "Design + frontend",
   "url": "https://cutshort.io/job/Senior-Product-Design-Engineer-Bengaluru-Bangalore-NeoGenCode-Technologies-Pvt-Ltd-IHD4CSNt",
   "note": "Hybrid · needs coding · Recruiter",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer",
   "company": "Namma Yatri",
   "portal": "LinkedIn",
   "posted": "2026-09-24",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Mobility",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-namma-yatri-4469395474",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "UX Designer 2",
   "company": "Nutanix",
   "portal": "LinkedIn",
   "posted": "2026-09-24",
   "exp": "2+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Cloud Software",
   "url": "https://in.linkedin.com/jobs/view/ux-designer-2-at-nutanix-4469705161",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer | Early-Stage MusicTech Portfolio Company",
   "company": "Peak XV Partners",
   "portal": "LinkedIn",
   "posted": "2026-09-24",
   "exp": "5–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "MusicTech",
   "url": "https://in.linkedin.com/jobs/view/product-designer-early-stage-musictech-portfolio-company-at-peak-xv-partners-4469696097",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "User Experience Designer",
   "company": "UST",
   "portal": "LinkedIn",
   "posted": "2026-09-24",
   "exp": "2-5 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Automotive",
   "url": "https://in.linkedin.com/jobs/view/user-experience-designer-at-ust-4469690424",
   "note": "",
   "firstSeen": "2026-10-04"
  },
  {
   "title": "Senior User Experience Designer",
   "company": "HCLTech",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "IT services",
   "url": "https://in.linkedin.com/jobs/view/senior-user-experience-designer-at-hcltech-4469343122",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer II",
   "company": "Nielsen",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Data, media",
   "url": "https://in.linkedin.com/jobs/view/product-designer-ii-at-nielsen-4459958590",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer II",
   "company": "JioHotstar",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Media, streaming",
   "url": "https://in.linkedin.com/jobs/view/product-designer-ii-at-jiohotstar-4468986566",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Staff Product Designer",
   "company": "ServiceTitan",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Vertical SaaS",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-servicetitan-4470922678",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "UX Designer - C3 - CXP",
   "company": "Valtech",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "5–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Experience Innovation",
   "url": "https://in.linkedin.com/jobs/view/ux-designer-c3-cxp-at-valtech-4461735412",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead Product Designer",
   "company": "Meesho",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "6+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "E-commerce",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-meesho-4470985311",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Group Manger - Experience Design",
   "company": "Infosys",
   "portal": "LinkedIn",
   "posted": "2026-09-23",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Enterprise Products",
   "url": "https://in.linkedin.com/jobs/view/group-manger-experience-design-at-infosys-4460692927",
   "note": "Hybrid",
   "firstSeen": "2026-10-04"
  },
  {
   "title": "Product Designer (UI/UX)",
   "company": "Lyzr AI",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "AI agents",
   "url": "https://in.linkedin.com/jobs/view/product-designer-ui-ux-at-lyzr-ai-4468516680",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior UX Designer",
   "company": "MakeMyTrip",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "4–6 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Travel",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-at-makemytrip-4471888686",
   "note": "Second opening posted 2 weeks ago",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "Healthify",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Health, consumer",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-healthify-4470463498",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "Menlo Security",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Cybersecurity, B2B",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-menlo-security-inc-4452406203",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "Think Design Collaborative",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Design agency",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-think-design-collaborative-4470251425",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer – Fi Admin",
   "company": "Candescent",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Banking software",
   "url": "https://in.linkedin.com/jobs/view/product-designer-fi-admin-at-candescent-4470284182",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Lead – Product Designer",
   "company": "Freshworks",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "B2B SaaS",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-freshworks-4467044606",
   "note": "2 openings",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Lead Product Designer",
   "company": "Josys",
   "portal": "LinkedIn",
   "posted": "2026-09-22",
   "exp": "5–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "IT management SaaS",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-josys-4469040520",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "JazzX AI",
   "portal": "LinkedIn",
   "posted": "2026-09-21",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-jazzx-ai-4467375690",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Lead Product Designer",
   "company": "noon",
   "portal": "LinkedIn",
   "posted": "2026-09-21",
   "exp": "6+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "E-commerce",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-noon-4469899160",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead UX Designer",
   "company": "Consilio LLC",
   "portal": "LinkedIn",
   "posted": "2026-09-21",
   "exp": "8+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Legal Tech",
   "url": "https://in.linkedin.com/jobs/view/lead-ux-designer-at-consilio-llc-4469913386",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UX Designer, YouTube Creator Support",
   "company": "Google",
   "portal": "LinkedIn",
   "posted": "2026-09-21",
   "exp": "4 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI",
   "url": "https://in.linkedin.com/jobs/view/ux-designer-youtube-creator-support-at-google-4468499694",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Manager, Product Design: AI Products",
   "company": "New Relic",
   "portal": "LinkedIn",
   "posted": "2026-09-21",
   "exp": "8+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "AI Products",
   "url": "https://in.linkedin.com/jobs/view/manager-product-design-ai-products-at-new-relic-4469882400",
   "note": "In office",
   "firstSeen": "2026-10-04"
  },
  {
   "title": "Senior Product Designer",
   "company": "AiDASH",
   "portal": "LinkedIn",
   "posted": "2026-09-20",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI, climate",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-aidash-4469804820",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Principal UX Designer (NetSec)",
   "company": "Palo Alto Networks",
   "portal": "LinkedIn",
   "posted": "2026-09-20",
   "exp": "10+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Cybersecurity",
   "url": "https://in.linkedin.com/jobs/view/principal-ux-designer-netsec-at-palo-alto-networks-4402818442",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Product Designer",
   "company": "Adobe",
   "portal": "LinkedIn",
   "posted": "2026-09-19",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Creative software",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-adobe-4321974489",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Design Engineer (Design, Frontend)",
   "company": "Staffnix",
   "portal": "Cutshort",
   "posted": "2026-09-19",
   "exp": "4–8 yrs",
   "payMinL": 40,
   "payMaxL": 50,
   "level": "Senior",
   "domain": "Design + frontend",
   "url": "https://cutshort.io/job/Senior-Product-Design-Engineer-Design-Frontend-Bengaluru-Bangalore-Staffnixcom-kbG17zf9",
   "note": "Recruiter · needs coding",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "Dash Hire",
   "portal": "Hirist",
   "posted": "2026-09-19",
   "exp": "4–7 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "",
   "url": "https://www.hirist.tech/j/senior-product-designer-1672893",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead Product Designer",
   "company": "Dash Hire",
   "portal": "Hirist",
   "posted": "2026-09-19",
   "exp": "7–12 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "",
   "url": "https://www.hirist.tech/j/lead-product-designer-1672891",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UI / UX designer",
   "company": "Emplay",
   "portal": "Wellfound",
   "posted": "2026-09-18",
   "exp": "3 yrs",
   "payMinL": 3,
   "payMaxL": 6.5,
   "level": "Mid",
   "domain": "B2B",
   "url": "https://wellfound.com/jobs/4751198-ui-ux-designer",
   "note": "Remote",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Yulu",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "EV mobility",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-yulu-4468606404",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "Xometry",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "B2B marketplace",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-xometry-4461334468",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Staff Product Designer",
   "company": "JazzX AI",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "AI",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-jazzx-ai-4463950753",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer 2",
   "company": "Truemeds",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Health, pharmacy",
   "url": "https://in.linkedin.com/jobs/view/product-designer-2-at-truemeds-4463973910",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer – AI and Enterprise Software",
   "company": "Thermo Fisher Scientific",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Life sciences, enterprise",
   "url": "https://in.linkedin.com/jobs/view/product-designer-ai-and-enterprise-software-job-posting-title-here-at-thermo-fisher-scientific-4464274964",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Principal Product Designer",
   "company": "Epicor",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Enterprise software",
   "url": "https://in.linkedin.com/jobs/view/principal-product-designer-at-epicor-4428814504",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "UI/UX Designer",
   "company": "Gnapi Technologies",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "5+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "IT Services",
   "url": "https://in.linkedin.com/jobs/view/ui-ux-designer-at-gnapi-technologies-4469153014",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Design Manager - UX, Product Design",
   "company": "PhonePe",
   "portal": "LinkedIn",
   "posted": "2026-09-18",
   "exp": "7–10 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Fintech",
   "url": "https://in.linkedin.com/jobs/view/product-design-manager-ux-product-design-at-phonepe-4458093175",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Head - Product Design",
   "company": "HR LOBBY",
   "portal": "Hirist",
   "posted": "2026-09-18",
   "exp": "7–10 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "",
   "url": "https://www.hirist.tech/j/head-product-design-7-10-yrs-1672570",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UI/UX Designer - Figma",
   "company": "Vedantu Innovations",
   "portal": "Hirist",
   "posted": "2026-09-18",
   "exp": "4–7 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "",
   "url": "https://www.hirist.tech/j/vedantu-innovations-senior-uiux-designer-figma-1672534",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead I – UX Design",
   "company": "UST",
   "portal": "LinkedIn",
   "posted": "2026-09-17",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "IT services",
   "url": "https://in.linkedin.com/jobs/view/lead-i-ux-design-at-ust-4448073143",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer - Figma",
   "company": "Employee Forums",
   "portal": "Hirist",
   "posted": "2026-09-17",
   "exp": "3–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "",
   "url": "https://www.hirist.tech/j/senior-product-designer-figma-1672222",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Staff Product Designer",
   "company": "JioStar",
   "portal": "LinkedIn",
   "posted": "2026-09-16",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Media, streaming",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-jiostar-4465966715",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "UI/UX Designer",
   "company": "Ecolab",
   "portal": "LinkedIn",
   "posted": "2026-09-16",
   "exp": "3+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Enterprise Software",
   "url": "https://in.linkedin.com/jobs/view/ui-ux-designer-at-ecolab-4468254051",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UI/UX Designer",
   "company": "JOOLA",
   "portal": "LinkedIn",
   "posted": "2026-09-16",
   "exp": "6-10+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "E-commerce",
   "url": "https://in.linkedin.com/jobs/view/ui-ux-designer-at-joola-4467951913",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Eloelo",
   "portal": "LinkedIn",
   "posted": "2026-09-16",
   "exp": "4-6 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Content, Social",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-eloelo-4466848159",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer (UX/UI)",
   "company": "Revun",
   "portal": "LinkedIn",
   "posted": "2026-09-15",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "SaaS",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-ux-ui-at-revun-4458703085",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "Mumzworld",
   "portal": "LinkedIn",
   "posted": "2026-09-15",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "E-commerce",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-mumzworld-com-4466158632",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior UX Designer",
   "company": "Myntra",
   "portal": "LinkedIn",
   "posted": "2026-09-15",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fashion e-commerce",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-at-myntra-4448859154",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer",
   "company": "Ema",
   "portal": "LinkedIn",
   "posted": "2026-09-15",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "AI, enterprise",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-ema-4465940221",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer III - Adobe Creative Suite",
   "company": "HyrMe",
   "portal": "Hirist",
   "posted": "2026-09-15",
   "exp": "5–10 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Creative Tools",
   "url": "https://www.hirist.tech/j/product-designer-iii-adobe-creative-suite-5-10-yrs-1671480",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "noon",
   "portal": "LinkedIn",
   "posted": "2026-09-14",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "E-commerce",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-noon-4467030748",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "UX Designer (2 to 4 years)",
   "company": "athenahealth",
   "portal": "LinkedIn",
   "posted": "2026-09-14",
   "exp": "2–4 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Healthcare",
   "url": "https://in.linkedin.com/jobs/view/ux-designer-2-to-4-years-at-athenahealth-4465865455",
   "note": "",
   "firstSeen": "2026-10-04"
  },
  {
   "title": "Senior Product Designer",
   "company": "Rapido",
   "portal": "LinkedIn",
   "posted": "2026-09-11",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Mobility, consumer",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-rapido-4464865223",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Platform Product Designer",
   "company": "JazzX AI",
   "portal": "LinkedIn",
   "posted": "2026-09-11",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "AI platform",
   "url": "https://in.linkedin.com/jobs/view/platform-product-designer-at-jazzx-ai-4463970068",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Lead Product Designer",
   "company": "FOXO",
   "portal": "Wellfound",
   "posted": "2026-09-11",
   "exp": "8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Longevity",
   "url": "https://wellfound.com/jobs/4689777-lead-product-designer",
   "note": "In office",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer",
   "company": "WorkIndia",
   "portal": "LinkedIn",
   "posted": "2026-09-11",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Jobs marketplace",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-workindia-4465632362",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior UX/UI Designer",
   "company": "4S Advisory",
   "portal": "Hirist",
   "posted": "2026-09-11",
   "exp": "5–7 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "",
   "url": "https://www.hirist.tech/j/senior-uxui-designer-1670903",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UI/UX Designer",
   "company": "Indegene",
   "portal": "Hirist",
   "posted": "2026-09-11",
   "exp": "5–10 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "",
   "url": "https://www.hirist.tech/j/indegene-senior-uiux-designer-1670625",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Sr UX Designer – Advanced AI",
   "company": "Target",
   "portal": "LinkedIn",
   "posted": "2026-09-10",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Retail, AI",
   "url": "https://in.linkedin.com/jobs/view/sr-ux-designer-advanced-ai-at-target-4460298097",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior User Experience Designer",
   "company": "redBus",
   "portal": "LinkedIn",
   "posted": "2026-09-10",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Travel",
   "url": "https://in.linkedin.com/jobs/view/senior-user-experience-designer-at-redbus-4464193049",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "Tekion",
   "portal": "LinkedIn",
   "posted": "2026-09-10",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Automotive SaaS",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-tekion-corp-4463481049",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer",
   "company": "Greytip (greytHR)",
   "portal": "LinkedIn",
   "posted": "2026-09-10",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "HR SaaS",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-greytip-software-private-limited-4465621168",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer II",
   "company": "Tekion",
   "portal": "LinkedIn",
   "posted": "2026-09-10",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Automotive SaaS",
   "url": "https://in.linkedin.com/jobs/view/product-designer-ii-at-tekion-corp-4463471044",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "Connect and Heal Primary Care",
   "portal": "Hirist",
   "posted": "2026-09-10",
   "exp": "5–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Healthcare",
   "url": "https://www.hirist.tech/j/senior-product-designer-1670450",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer - Figma",
   "company": "Samta Infotech",
   "portal": "Hirist",
   "posted": "2026-09-10",
   "exp": "6–9 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Product Design",
   "url": "https://www.hirist.tech/j/samta-product-designer-figma-1670280",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer - Web Design",
   "company": "Arting Digital",
   "portal": "Hirist",
   "posted": "2026-09-10",
   "exp": "5–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Web Design",
   "url": "https://www.hirist.tech/j/senior-product-designer-web-design-1670353",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UI/UX Designer",
   "company": "Netapp",
   "portal": "Hirist",
   "posted": "2026-09-10",
   "exp": "5–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "",
   "url": "https://www.hirist.tech/j/netapp-uiux-designer-1670576",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Lenskart",
   "portal": "LinkedIn",
   "posted": "2026-09-09",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Retail, e-commerce",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-lenskart-com-4463034182",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Lead Product Designer",
   "company": "GREYTIP SOFTWARE PRIVATE LIMITED",
   "portal": "LinkedIn",
   "posted": "2026-09-09",
   "exp": "8–10 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "HR Tech SaaS",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-greytip-software-private-limited-4464972772",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead Product Designer - Mobile Platform",
   "company": "FOXO",
   "portal": "Hirist",
   "posted": "2026-09-09",
   "exp": "7–10 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Mobile Platform",
   "url": "https://www.hirist.tech/j/foxo-lead-product-designer-mobile-platform-1669796",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Fam",
   "portal": "LinkedIn",
   "posted": "2026-09-08",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-fam-4463247310",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior UX Designer – India",
   "company": "Anatta",
   "portal": "LinkedIn",
   "posted": "2026-09-08",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Shopify agency",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-india-at-anatta-shopify-platinum-partner-4463065016",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer",
   "company": "Nava",
   "portal": "LinkedIn",
   "posted": "2026-09-07",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Startup",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-nava-4462940225",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer - Mobile App Designing",
   "company": "Vontier",
   "portal": "Hirist",
   "posted": "2026-09-07",
   "exp": "7–11 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Mobile App",
   "url": "https://www.hirist.tech/j/vontier-senior-product-designer-mobile-app-designing-1669186",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer",
   "company": "Bridgestone Americas",
   "portal": "LinkedIn",
   "posted": "2026-09-06",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Enterprise",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-at-bridgestone-americas-4462680228",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Lead Product Designer",
   "company": "PhysicsWallah",
   "portal": "LinkedIn",
   "posted": "2026-09-04",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Edtech",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-pw-physicswallah-4463346830",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Lead Product Designer",
   "company": "Emirates NBD",
   "portal": "LinkedIn",
   "posted": "2026-09-04",
   "exp": "5+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Fintech",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-emirates-nbd-4461158680",
   "note": "",
   "firstSeen": "2026-10-04"
  },
  {
   "title": "Senior User Experience Designer II",
   "company": "Schneider Electric",
   "portal": "LinkedIn",
   "posted": "2026-09-03",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Energy, enterprise",
   "url": "https://in.linkedin.com/jobs/view/senior-user-experience-designer-ii-at-schneider-electric-4461627521",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "UI/UX Designer - Prototyping Tools",
   "company": "Outsourcing",
   "portal": "Hirist",
   "posted": "2026-09-03",
   "exp": "10–15 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Prototyping Tools",
   "url": "https://www.hirist.tech/j/uiux-designer-prototyping-tools-10-15-yrs-1668372",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Experience Designer, SC Design (UI/UX)",
   "company": "Standard Chartered",
   "portal": "LinkedIn",
   "posted": "2026-09-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Banking",
   "url": "https://in.linkedin.com/jobs/view/senior-experience-designer-sc-design-ui-ux-at-standard-chartered-india-4460244922",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer",
   "company": "Get My Parking",
   "portal": "Wellfound",
   "posted": "2026-09-02",
   "exp": "5 yrs",
   "payMinL": 15,
   "payMaxL": 20,
   "level": "Senior",
   "domain": "AI",
   "url": "https://wellfound.com/jobs/747214-senior-product-designer",
   "note": "In office",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "AI Product Designer — Founding Member, BrandBrahma",
   "company": "BrandBrahma",
   "portal": "Wellfound",
   "posted": "2026-09-02",
   "exp": "3 yrs",
   "payMinL": 8,
   "payMaxL": 20,
   "level": "Mid",
   "domain": "AI",
   "url": "https://wellfound.com/jobs/4505597-product-designer-founding-member-brandbrahma",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Lead Product Designer",
   "company": "Dashverse",
   "portal": "LinkedIn",
   "posted": "2026-09-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Consumer AI",
   "url": "https://in.linkedin.com/jobs/view/lead-product-designer-at-dashverse-4448825208",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "SE Intel UX UI Designer",
   "company": "Schneider Electric",
   "portal": "LinkedIn",
   "posted": "2026-09-01",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Digital Experience",
   "url": "https://in.linkedin.com/jobs/view/se-intel-ux-ui-designer-at-schneider-electric-4460622458",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UX Engineer - Prototype/Wireframe Design",
   "company": "Workplace",
   "portal": "Hirist",
   "posted": "2026-09-01",
   "exp": "3–6 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Tech",
   "url": "https://www.hirist.tech/j/ux-engineer-prototypewireframe-design-1667267",
   "note": "needs coding",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UI/UX Design Lead - Digital Banking Domain",
   "company": "HiPos Consulting",
   "portal": "Hirist",
   "posted": "2026-08-31",
   "exp": "8–10 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Digital Banking",
   "url": "https://www.hirist.tech/j/uiux-design-lead-digital-banking-domain-1667179",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer",
   "company": "Vistaprint",
   "portal": "Hirist",
   "posted": "2026-08-26",
   "exp": "7–12 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "",
   "url": "https://www.hirist.tech/j/senior-ux-designer-1666137",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UI/UX Designer - Figma",
   "company": "Talview",
   "portal": "Hirist",
   "posted": "2026-08-26",
   "exp": "4–6 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "",
   "url": "https://www.hirist.tech/j/talview-senior-uiux-designer-figma-1665964",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer - Figma/Adobe XD",
   "company": "Scaling Theory Technologies",
   "portal": "Hirist",
   "posted": "2026-08-22",
   "exp": "4–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "",
   "url": "https://www.hirist.tech/j/senior-product-designer-figmaadobe-xd-1664803",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Founding Product Designer - Figma",
   "company": "Scaling Theory Technologies",
   "portal": "Hirist",
   "posted": "2026-08-20",
   "exp": "3–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Product Design",
   "url": "https://www.hirist.tech/j/founding-product-designer-figma-1664849",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UX Designer - Product Design",
   "company": "ChayanikaRecruittech",
   "portal": "Hirist",
   "posted": "2026-08-20",
   "exp": "2–6 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Product Design",
   "url": "https://www.hirist.tech/j/ux-designer-product-design-1664647",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UX Designer - Systems & Interaction Design",
   "company": "HR Works Consultancy",
   "portal": "Hirist",
   "posted": "2026-08-20",
   "exp": "2–6 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Systems Design",
   "url": "https://www.hirist.tech/j/ux-designer-systems-interaction-design-1664783",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Sarvam",
   "portal": "LinkedIn",
   "posted": "2026-08-19",
   "exp": "4+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI",
   "url": "https://in.linkedin.com/jobs/view/product-designer-at-sarvam-4456176299",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UX/UI Designer",
   "company": "Apple",
   "portal": "LinkedIn",
   "posted": "2026-08-19",
   "exp": "1+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Manufacturing Data",
   "url": "https://in.linkedin.com/jobs/view/ux-ui-designer-at-apple-4454938841",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer - Figma",
   "company": "Success Pact Consulting",
   "portal": "Hirist",
   "posted": "2026-08-17",
   "exp": "6–10 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "",
   "url": "https://www.hirist.tech/j/senior-product-designer-figma-1663740",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Loop Health - Product Designer",
   "company": "Invoq Healthcare",
   "portal": "Hirist",
   "posted": "2026-08-14",
   "exp": "1–3 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Healthcare",
   "url": "https://www.hirist.tech/j/loop-health-product-designer-1663264",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Hevo Data",
   "portal": "Company site",
   "posted": "2026-08-13",
   "exp": "4–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Data SaaS, AI-first",
   "url": "https://jobs.lever.co/hevodata/3c22a84f-7eb6-4105-aa3b-7698322a98af",
   "note": "On-site 5 days, HSR Layout · also on LinkedIn",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Lead Product Designer - Interaction Design",
   "company": "ALLEN Career Institute",
   "portal": "Hirist",
   "posted": "2026-08-13",
   "exp": "5–7 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Education",
   "url": "https://www.hirist.tech/j/allen-lead-product-designer-interaction-design-1662873",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "StockGro",
   "portal": "LinkedIn",
   "posted": "2026-08-07",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech, investing",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-stockgro-4430921229",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Publicis Sapient - Product Designer - Figma",
   "company": "Sapient (publicissapient)",
   "portal": "Hirist",
   "posted": "2026-08-07",
   "exp": "5–10 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Product Design",
   "url": "https://www.hirist.tech/j/publicis-sapient-product-designer-figma-1661228",
   "note": "Hybrid",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "THINK41 TECHNOLOGIES PRIVATE LIMITED",
   "portal": "Hirist",
   "posted": "2026-08-06",
   "exp": "1–4 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "",
   "url": "https://www.hirist.tech/j/think41-product-designer-1-4-yrs-1661149",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Gilbarco Veeder Root",
   "portal": "Hirist",
   "posted": "2026-08-06",
   "exp": "5–9 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "",
   "url": "https://www.hirist.tech/j/gilbarco-veeder-root-senior-product-designer-5-9-yrs-1661091",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "Finkraft",
   "portal": "LinkedIn",
   "posted": "2026-08-05",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Fintech, B2B",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-finkraft-4433468110",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "UI/UX Designer",
   "company": "Wesence",
   "portal": "Wellfound",
   "posted": "2026-08-04",
   "exp": "3 yrs",
   "payMinL": 6,
   "payMaxL": 7.2,
   "level": "Mid",
   "domain": "Intelligent Systems",
   "url": "https://wellfound.com/jobs/4718643-ui-ux-product-designer",
   "note": "In office",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "Corvee",
   "portal": "Wellfound",
   "posted": "2026-08-04",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "B2B",
   "url": "https://wellfound.com/jobs/3344993-product-designer",
   "note": "",
   "firstSeen": "2026-10-04"
  },
  {
   "title": "Product Designer",
   "company": "FOXO",
   "portal": "Wellfound",
   "posted": "2026-08-03",
   "exp": "4 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Longevity",
   "url": "https://wellfound.com/jobs/4053124-product-designer",
   "note": "In office",
   "firstSeen": "2026-10-03"
  },
  {
   "title": "Staff Product Designer",
   "company": "EarnIn",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "B2C",
   "url": "https://in.linkedin.com/jobs/view/staff-product-designer-at-earnin-4443581994",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Staff/Principal Product Designer, Partnerships",
   "company": "Ethos",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "Insurance",
   "url": "https://wellfound.com/jobs/4670517-staff-principal-product-designer-partnerships",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior UI/UX Designer",
   "company": "ENFLIX",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "5 yrs",
   "payMinL": 11,
   "payMaxL": 14,
   "level": "Senior",
   "domain": "Entertainment",
   "url": "https://wellfound.com/jobs/4479275-senior-ui-ux-designer",
   "note": "In office",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product UI/UX Designer",
   "company": "Outdoo AI",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "2 yrs",
   "payMinL": 20,
   "payMaxL": 30,
   "level": "Senior",
   "domain": "AI",
   "url": "https://wellfound.com/jobs/2976208-senior-product-ui-ux-designer",
   "note": "In office",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Product Designer",
   "company": "Fireflies.ai",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "3 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "B2B",
   "url": "https://wellfound.com/jobs/3281427-product-designer",
   "note": "Remote",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer / UI-UX Designer",
   "company": "rooh",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "3 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Growth",
   "url": "https://wellfound.com/jobs/4418963-product-designer-ui-ux-designer",
   "note": "Remote",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "UI/UX Designer (Engineering Platforms)",
   "company": "ENGINPILOT",
   "portal": "Wellfound",
   "posted": "2026-08-02",
   "exp": "3 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Physical Assets",
   "url": "https://wellfound.com/jobs/4435452-ui-ux-designer-engineering-platforms",
   "note": "In office needs coding",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior Product Designer",
   "company": "GreyLabs AI",
   "portal": "LinkedIn",
   "posted": "2026-07-31",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI, conversation analytics",
   "url": "https://in.linkedin.com/jobs/view/senior-product-designer-at-greylabs-ai-4447513416",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior UI/UX Designer",
   "company": "ADA",
   "portal": "LinkedIn",
   "posted": "2026-07-31",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Digital agency",
   "url": "https://in.linkedin.com/jobs/view/senior-ui-ux-designer-at-ada-4446996414",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer - NID/IIT",
   "company": "TresVista",
   "portal": "Hirist",
   "posted": "2026-07-31",
   "exp": "7–10 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "",
   "url": "https://www.hirist.tech/j/tresvista-senior-product-designer-nidiit-1659581",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer - Figma/Adobe XD",
   "company": "HyrMe",
   "portal": "Hirist",
   "posted": "2026-07-28",
   "exp": "2–5 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Product Design",
   "url": "https://www.hirist.tech/j/product-designer-figmaadobe-xd-1658307",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Sr. UX Designer",
   "company": "Eightfold AI",
   "portal": "LinkedIn",
   "posted": "2026-07-25",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "AI, HR tech",
   "url": "https://in.linkedin.com/jobs/view/sr-ux-designer-at-eightfold-ai-4445326692",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Lead UX Designer - Adobe Creative Suite",
   "company": "ACCOLITE DIGITAL INDIA PRIVATE LIMITED",
   "portal": "Hirist",
   "posted": "2026-07-24",
   "exp": "7–12 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Digital",
   "url": "https://www.hirist.tech/j/lead-ux-designer-adobe-creative-suite-1657439",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer, RBS",
   "company": "Amazon",
   "portal": "LinkedIn",
   "posted": "2026-07-23",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "E-commerce",
   "url": "https://in.linkedin.com/jobs/view/senior-ux-designer-rbs-at-amazon-4455794253",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Senior Product Designer - Figma",
   "company": "HyrMe",
   "portal": "Hirist",
   "posted": "2026-07-22",
   "exp": "4–6 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "",
   "url": "https://www.hirist.tech/j/senior-product-designer-figma-1656508",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Director - Product Design",
   "company": "HyrMe",
   "portal": "Hirist",
   "posted": "2026-07-22",
   "exp": "10–16 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Staff",
   "domain": "",
   "url": "https://www.hirist.tech/j/director-product-design-10-16-yrs-1667983",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "A&CD - UX Design Lead (Contract",
   "company": "Alstom",
   "portal": "LinkedIn",
   "posted": "2026-07-21",
   "exp": "8+ yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "Transportation",
   "url": "https://in.linkedin.com/jobs/view/a-cd-ux-design-lead-contract-at-alstom-4440489795",
   "note": "Contract",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer - Figma/Wireframing Tools",
   "company": "HyrMe",
   "portal": "Hirist",
   "posted": "2026-07-21",
   "exp": "4–8 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "Product Design",
   "url": "https://www.hirist.tech/j/product-designer-figmawireframing-tools-1656101",
   "note": "Recruiter",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Product Designer",
   "company": "FirstClub",
   "portal": "Hirist",
   "posted": "2026-07-20",
   "exp": "3–5 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Mid",
   "domain": "",
   "url": "https://www.hirist.tech/j/firstclub-product-designer-1655716",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UI/UX Designer",
   "company": "Squadra Media",
   "portal": "LinkedIn",
   "posted": "2026-07-15",
   "exp": "",
   "payMinL": null,
   "payMaxL": null,
   "level": "Senior",
   "domain": "Media",
   "url": "https://in.linkedin.com/jobs/view/senior-ui-ux-designer-at-squadra-media-4440205926",
   "note": "",
   "firstSeen": "2026-10-01"
  },
  {
   "title": "Straive - Lead UX Designer",
   "company": "SPI TECHNOLOGIES INDIA PRIVATE LIMITED",
   "portal": "Hirist",
   "posted": "2026-07-15",
   "exp": "7–11 yrs",
   "payMinL": null,
   "payMaxL": null,
   "level": "Lead",
   "domain": "",
   "url": "https://www.hirist.tech/j/straive-lead-ux-designer-1654187",
   "note": "",
   "firstSeen": "2026-10-02"
  },
  {
   "title": "Senior UX Designer",
   "company": "Mirorin",
   "portal": "Cutshort",
   "posted": "2026-06-22",
   "exp": "5+ yrs",
   "payMinL": 6,
   "payMaxL": 9,
   "level": "Senior",
   "domain": "FemTech",
   "url": "https://cutshort.io/jobs/product-design-jobs",
   "note": "",
   "firstSeen": "2026-10-02"
  }
 ]
};
